/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nexvoo_rsajni_RsaJni */

#ifndef _Included_com_nexvoo_rsajni_RsaJni
#define _Included_com_nexvoo_rsajni_RsaJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nexvoo_rsajni_RsaJni
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nexvoo_rsajni_RsaJni_encrypt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_nexvoo_rsajni_RsaJni
 * Method:    decrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nexvoo_rsajni_RsaJni_decrypt
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
